### PR TITLE
Update URLs to new repo link

### PR DESCRIPTION
**Pull request by kaitj**
## Proposed changes

Github should automatically redirect to the new URL, but updating the repository links to point to the moved URL (which should also update the metadata over on PyPI on next release).

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [x] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

### CODE REVIEW

**Comment by pvandyken** [comment]
Ah, good catch, thanks. I assume the diffs across all the md files is the result of some linter?

**Comment by kaitj** [comment]
> Ah, good catch, thanks. I assume the diffs across all the md files is the result of some linter?

Yeah, I have my VSCode setup to save on format, which I just disabled - just going through and manually fixing some of those changes - namely the double tilde to single tilde. The other ones are more minor:

* Change from `*` to `_` italics
* Spacing from markdown header to body

**Comment by pvandyken** [comment]
Gotcha, I don't think it's a big deal, those double ticks probably should be fixed anyway

**Comment by kaitj** [comment]
Ahh, well I just went through and  changed them back, but can easily just let my VSCode fix those again if you rather them be single tick.

**Review by pvandyken — APPROVED** [review]
LGTM, merge whenever you like

**Pull request merged**
